import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getTripById } from '../services/api';
import toast from 'react-hot-toast';

export default function TripDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [trip, setTrip] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getTripById(id)
      .then(({ data }) => setTrip(data))
      .catch(() => { toast.error('Trip not found'); navigate('/dashboard'); })
      .finally(() => setLoading(false));
  }, [id, navigate]);

  if (loading) return <div className="loading-screen"><div className="spinner" /></div>;
  if (!trip) return null;

  const totalCost = trip.itineraries?.reduce((sum, d) => sum + (d.estimatedDayCost || 0), 0) || 0;

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 24 }}>
        <button className="btn btn-secondary" onClick={() => navigate('/dashboard')}>← Back</button>
        <div>
          <h1 style={{ fontSize: 26, fontWeight: 800 }}>📍 {trip.destination}</h1>
          <p style={{ color: 'var(--text-muted)', fontSize: 14 }}>
            {trip.durationDays} days · Budget: {trip.budget} {trip.currency} · Generated by AI
          </p>
        </div>
      </div>

      {/* Summary card */}
      <div className="card" style={{ marginBottom: 24, display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16 }}>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 28, fontWeight: 800, color: 'var(--primary)' }}>{trip.durationDays}</div>
          <div style={{ color: 'var(--text-muted)', fontSize: 13 }}>Days Planned</div>
        </div>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 28, fontWeight: 800, color: 'var(--success)' }}>
            {trip.currency} {totalCost.toLocaleString()}
          </div>
          <div style={{ color: 'var(--text-muted)', fontSize: 13 }}>Estimated Total Cost</div>
        </div>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 28, fontWeight: 800, color: 'var(--secondary)' }}>{trip.itineraries?.length || 0}</div>
          <div style={{ color: 'var(--text-muted)', fontSize: 13 }}>Days in Itinerary</div>
        </div>
      </div>

      {/* Day-by-day itinerary */}
      {trip.itineraries?.map(day => (
        <div className="itinerary-day" key={day.id}>
          <div className="day-header">Day {day.dayNumber}</div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16 }}>
            <div className="activity-block">
              <h4>🌅 Morning</h4>
              <p>{day.morningActivity}</p>
            </div>
            <div className="activity-block">
              <h4>☀️ Afternoon</h4>
              <p>{day.afternoonActivity}</p>
            </div>
            <div className="activity-block">
              <h4>🌙 Evening</h4>
              <p>{day.eveningActivity}</p>
            </div>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginTop: 16 }}>
            <div className="activity-block">
              <h4>🏨 Hotel</h4>
              <p>{day.hotelSuggestion}</p>
            </div>
            <div className="activity-block">
              <h4>🍽️ Restaurants</h4>
              <p>{day.restaurantSuggestions}</p>
            </div>
          </div>

          <div className="day-footer">
            <div className="activity-block" style={{ margin: 0 }}>
              <h4>💡 Travel Tip</h4>
              <p>{day.travelTips}</p>
            </div>
            <div className="day-cost">
              {trip.currency} {day.estimatedDayCost?.toLocaleString()}
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}
